name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Setup
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 mypy
      - name: Black
        uses: psf/black@stable
      - name: Flake8
        run: flake8 nopdb
      - name: Mypy
        run: mypy nopdb
