name: Test

on: [push, pull_request]

jobs:
  doctest:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.6", "3.9", "pypy-3.6"]
    name: Doctest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r docs/requirements.txt
      - name: Doctest
        run: cd docs && make doctest
